### ISSUE TITLE
show jshint rule related to the error in stylish output

### ISSUE THREAD

**Issue by obuckley-kenzan** [sindresorhus/jshint-stylish#28] opened 2015-11-14 22:50 UTC
Not sure if this would be for here, the jshint team, or the gulp-jshint team, but would it be possible to see the jshint rule related to the thrown error, either by default or as config option?

for example, if the error is 
`line 16  col 14  'cardPayment' is not defined.`

we would also see this as part of the output
`/* jshint -W117 */`

Thanks and keep up the great work!

**Comment by sindresorhus** [comment] 2015-11-15 07:36
Duplicate of #14.

**Closed by sindresorhus** 2015-11-15 07:36 UTC

**Comment by obuckley-kenzan** [comment] 2015-11-16 13:50
Thanks, will follow up with the gulp-jshint team
